---
version: "2"
##checks:
##  argument-count:
##    config:
##      threshold: 5
exclude_patterns:
  - "build/"
  - "docs/"
  - "bin/"
  - "vendor/"
  - "**/Tests/"
  - "**/Behat/"
  - "**/Resources/"
  - "**/vendor/"
  - "src/Korowai/Component/Ldap/Adapter/ExtLdap/LdapLink.php"
plugins:
  phpcodesniffer:
    enabled: true
