version: '3.2'
services:
  sphinx:
    build:
      context: ../docker/user
      args:
        KRW_IMG: "korowai/sphinx:${KRW_SPHINX_TAG:-latest}"
        KRW_UID: "${KRW_UID:-6789}"
        KRW_GID: "${KRW_GID:-6789}"
    ports:
      - "8000:8000"
    volumes:
      - ../:${KRW_CODE:-/code}
    user: "${KRW_UID:-6789}:${KRW_GID:-6789}"

  sami:
    build:
      context: ../docker/user
      args:
        KRW_IMG: "korowai/sami:${KRW_SAMI_TAG:-latest}"
        KRW_UID: "${KRW_UID:-6789}"
        KRW_GID: "${KRW_GID:-6789}"
    ports:
      - "8001:8001"
    volumes:
      - ../:${KRW_CODE:-/code}
    user: "${KRW_UID:-6789}:${KRW_GID:-6789}"

  phpdoc:
    image: "phpdoc/phpdoc:${KRW_PHPDOC_TAG:-develop}"
    volumes:
      - ../:/data
    user: "${KRW_UID:-6789}:${KRW_GID:-6789}"
